apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
   repoURL: 'https://github.com/Bobejoo/ArgoCD.git'
   path: frontend
   targetRevision: HEAD
  destination:
   server: 'https://kubernetes.default.svc'
   namespace: default
  syncPolicy:
   automated: {}
